import 'package:flutter/material.dart'
    show Brightness, Color, ColorScheme, TextTheme, TextStyle, FontWeight;
import 'package:google_fonts/google_fonts.dart';

const ColorScheme quickPollLightColorScheme = ColorScheme.light(
  brightness: Brightness.light,
  primary: Color(0xFFFB8C00),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFD14218),
  primaryFixed: Color(0xFFFFDBD1),
  primaryFixedDim: Color(0xFFFFB5A1),
  onPrimaryFixed: Color(0xFF3B0900),
  onPrimaryFixedVariant: Color(0xFF882000),
  surfaceDim: Color(0xFFEFD4CE),
  surface: Color(0xFFFFFFFF),
  surfaceBright: Color(0xFFFFF8F6),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFFFF1ED),
  surfaceContainer: Color(0xFFFFE9E4),
  surfaceContainerHigh: Color(0xFFFEE2DB),
  surfaceContainerHighest: Color(0xFFF8DDD6),
  onSurface: Color(0xFF1E1E1E),
  onSurfaceVariant: Color(0xFF4D4D4D),
  outline: Color(0xFF8E7068),
  outlineVariant: Color(0xFFE2BFB5),
  secondary: Color(0xFF2A4759),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFF9B45),
  onSecondaryContainer: Color(0xFF6D3700),
  secondaryFixed: Color(0xFFFFDCC4),
  secondaryFixedDim: Color(0xFFFFB780),
  onSecondaryFixed: Color(0xFF2F1400),
  onSecondaryFixedVariant: Color(0xFF6F3800),
  tertiary: Color(0xFF309889),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFC9A83C),
  onTertiaryContainer: Color(0xFF4E3E00),
  tertiaryFixed: Color(0xFFFFE086),
  tertiaryFixedDim: Color(0xFFE6C355),
  onTertiaryFixed: Color(0xFF231B00),
  onTertiaryFixedVariant: Color(0xFF574500),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF93000A),
  inverseSurface: Color(0xFF3D2D28),
  onInverseSurface: Color(0xFFFFF5F2),
  inversePrimary: Color(0xFFFFB5A1),
  scrim: Color(0xFF000000),
  shadow: Color(0xFF000000),
);

const ColorScheme quickPollDarkColorScheme = ColorScheme.dark(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB5A1),
  onPrimary: Color(0xFF601400),
  primaryContainer: Color(0xFFF85E32),
  onPrimaryContainer: Color(0xFF140100),
  primaryFixed: Color(0xFFFFDBD1),
  primaryFixedDim: Color(0xFFFFB5A1),
  onPrimaryFixed: Color(0xFF3B0900),
  onPrimaryFixedVariant: Color(0xFF882000),
  surfaceDim: Color(0xFF1D100C),
  surface: Color(0xFF1D100C),
  surfaceBright: Color(0xFF463531),
  surfaceContainerLowest: Color(0xFF170B08),
  surfaceContainerLow: Color(0xFF261814),
  surfaceContainer: Color(0xFF2B1C18),
  surfaceContainerHigh: Color(0xFF362622),
  surfaceContainerHighest: Color(0xFF42312C),
  onSurface: Color(0xFFF8DDD6),
  onSurfaceVariant: Color(0xFFE2BFB5),
  outline: Color(0xFFA98A81),
  outlineVariant: Color(0xFF5A413A),
  secondary: Color(0xFFFFC295),
  onSecondary: Color(0xFF4E2600),
  secondaryContainer: Color(0xFFFF9B45),
  onSecondaryContainer: Color(0xFF6D3700),
  secondaryFixed: Color(0xFFFFDCC4),
  secondaryFixedDim: Color(0xFFFFB780),
  onSecondaryFixed: Color(0xFF2F1400),
  onSecondaryFixedVariant: Color(0xFF6F3800),
  tertiary: Color(0xFFE6C355),
  onTertiary: Color(0xFF3C2F00),
  tertiaryContainer: Color(0xFFC9A83C),
  onTertiaryContainer: Color(0xFF4E3E00),
  tertiaryFixed: Color(0xFFFFE086),
  tertiaryFixedDim: Color(0xFFE6C355),
  onTertiaryFixed: Color(0xFF231B00),
  onTertiaryFixedVariant: Color(0xFF574500),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  inverseSurface: Color(0xFFF8DDD6),
  onInverseSurface: Color(0xFF3D2D28),
  inversePrimary: Color(0xFFB22C00),
  scrim: Color(0xFF000000),
  shadow: Color(0xFF000000),
);

final TextTheme quickPollTextTheme = TextTheme(
  // Display
  displayLarge: GoogleFonts.roboto(
    fontSize: 57,
    height: 64 / 57,
    letterSpacing: -0.25,
    fontWeight: FontWeight.normal,
  ),
  displayMedium: GoogleFonts.roboto(
    fontSize: 45,
    height: 52 / 45,
    letterSpacing: 0,
    fontWeight: FontWeight.normal,
  ),
  displaySmall: GoogleFonts.roboto(
    fontSize: 36,
    height: 44 / 36,
    letterSpacing: 0,
    fontWeight: FontWeight.normal,
  ), // Headline
  headlineLarge: GoogleFonts.roboto(
    fontSize: 32,
    height: 40 / 32,
    letterSpacing: 0,
    fontWeight: FontWeight.w600,
  ),
  headlineMedium: GoogleFonts.roboto(
    fontSize: 28,
    height: 36 / 28,
    letterSpacing: 0,
    fontWeight: FontWeight.w400,
  ),
  headlineSmall: GoogleFonts.roboto(
    fontSize: 24,
    height: 32 / 24,
    letterSpacing: 0,
    fontWeight: FontWeight.w600,
  ), // Title
  titleLarge: GoogleFonts.roboto(
    fontSize: 22,
    height: 28 / 22,
    letterSpacing: 0,
    fontWeight: FontWeight.w400,
  ),
  titleMedium: GoogleFonts.roboto(
    fontSize: 16,
    height: 24 / 16,
    letterSpacing: 0.15,
    fontWeight: FontWeight.w500,
  ),
  titleSmall: GoogleFonts.roboto(
    fontSize: 14,
    height: 20 / 14,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
  ), // Label
  labelLarge: GoogleFonts.roboto(
    fontSize: 14,
    height: 20 / 14,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
  ),
  labelMedium: GoogleFonts.roboto(
    fontSize: 12,
    height: 16 / 12,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: GoogleFonts.roboto(
    fontSize: 11,
    height: 16 / 11,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
  ), // Body
  bodyLarge: GoogleFonts.roboto(
    fontSize: 16,
    height: 24 / 16,
    letterSpacing: 0.5,
    fontWeight: FontWeight.normal,
  ),
  bodyMedium: GoogleFonts.roboto(
    fontSize: 14,
    height: 20 / 14,
    letterSpacing: 0.25,
    fontWeight: FontWeight.normal,
  ),
  bodySmall: GoogleFonts.roboto(
    fontSize: 12,
    height: 16 / 12,
    letterSpacing: 0.4,
    fontWeight: FontWeight.normal,
  ),
);
